// js/vocabList3.js
export const vocabList3 = [
    [201, "もる", "盛る", "", "Bày biện, làm đầy"],
    [202, "へいぼんな", "へいぼんな", "BÌNH PHÀM", "Bình thường, thường"],
    [203, "そぼくな", "素朴な", "TỐ PHÁC", "Mộc mạc, đơn giản"],
    [204, "せいみつな", "精密な", "TINH MẬT", "Chính xác, chi tiết, tỉ mỉ"],
    [205, "きょくたんな", "極端な", "CỰC ĐOAN", "Cực đoan"],
    [206, "もうれつな", "猛烈な", "MÃNH LIỆT", "Mãnh liệt, mạnh"],
    [207, "げんじゅうな", "厳重な", "NGHIÊM TRỌNG", "Nghiêm trọng, nghiêm khắc"],
    [208, "じゅうぶんな", "十分な", "THẬP PHÂN", "Đầy đủ"],
    [209, "おおはばな", "大幅な", "ĐẠI PHÚC", "Khá, đáng kể, nhiều, mạnh"],
    [210, "ぼうだいな", "膨大な", "BÀNH ĐẠI", "Khổng lồ, bành trướng"],
    [211, "とぼしい", "乏しい", "PHẠP", "Nghèo, giới hạn"],
    [212, "わずかな", "僅かな", "CẬN", "Chút ít, chỉ, nhẹ, suýt"],
    [213, "かすかな", "微かな", "VI", "Loáng thoáng, nhỏ bé"],
    [214, "びみょうな", "微妙な", "VI DIỆU", "Sao sao đó, không rõ ràng"],
    [215, "きゅうげきな", "急激な", "CẤP KÍCH", "Đột ngột, gấp biến"],
    [216, "きゅうそくな", "急速な", "CẤP TỐC", "Cấp tốc, nhanh chóng"],
    [217, "きょうこうな", "強硬な", "CƯỜNG NGẠNH", "Ngoan cường, cứng rắn, cứng nhắc"],
    [218, "よけいな", "余計な", "DƯ KẾ", "Không cần thiết, vô nghĩa"],
    [219, "ふしんな", "不審な", "BẤT THẨM", "Nghi ngờ, đáng nghi"],
    [220, "こうしきな", "公式な", "CÔNG THỨC", "chính thức, công thức"],
    [221, "せいとうな", "正当な", "CHÍNH ĐƯỜNG", "chính đáng, đúng đắn, chính nghĩa"],
    [222, "せいじょうな", "正常な", "CHÍNH THƯỜNG", "thông thường, bình thường"],
    [223, "かんぺきな", "完璧な", "HOÀN BÍCH", "hoàn hảo, chuẩn mực"],
    [224, "かんけつな", "簡潔な", "GIẢN KHIẾT", "đơn giản, ngắn gọn, súc tích"],
    [225, "めいはくな", "明白な", "MINH BẠCH", "rõ ràng, hiển nhiên"],
    [226, "きゃっかんてきな", "客観的な", "KHÁCH QUAN ĐÍCH", "khách quan"],
    [227, "えんまんな", "円満な", "KHÚC", "viên mãn, êm đẹp"],
    [228, "ふかけつな", "不可欠な", "BẤT KHẢ KHIẾM", "không thể thiếu"],
    [229, "ゆうりな", "有利な", "HỮU LỢI", "có ích, có lợi"],
    [230, "ゆうぼうな", "有望な", "HỮU VỌNG", "có triển vọng, có tương lai"],
    [231, "まちどおしい", "待ち遠しい", "ĐÃI VIỄN", "mong chờ, mong đợi"],
    [232, "よろこばしい", "喜ばしい", "HỈ", "hạnh phúc, vui mừng"],
    [233, "のぞましい", "望ましい", "VỌNG", "được ưa chuộng, lý tưởng"],
    [234, "うたがわしい", "疑わしい", "NGHI", "nghi ngờ"],
    [235, "らっかんてきな", "楽観的な", "LẠC QUAN ĐÍCH", "lạc quan"],
    [236, "くすぐったい", "", "", "buồn (nhột)"],
    [237, "だるい", "", "", "mệt, uể oải"],
    [238, "ゆうりょくな", "有力な", "ƯU LỰC", "có ảnh hưởng lớn, có sức mạnh"],
    [239, "きんべんな", "勤勉な", "CẦN MIỄN", "cần cù, chăm chỉ"],
    [240, "れいせいな", "冷静な", "LÃNH TĨNH", "bình tĩnh, sáng suốt"],
    [241, "けんめいな", "賢明な", "HIỀN MINH", "thông minh, sáng suốt"],
    [242, "おんわな", "温和な・穏和な", "ÔN HÒA", "ôn hòa"],
    [243, "おおらかな", "大らかな", "ĐẠI", "rộng lượng, phóng khoáng"],
    [244, "ほがらかな", "朗らかな", "", "vô lo, vô nghĩ"],
    [245, "おおらかな", "大らかな", "ĐẠI", "cởi mở, không tiểu tiết"],
    [246, "おおらかな", "大らかな", "ĐẠI", "làm quá lên, phóng đại"],
    [247, "まえむきな", "前向きな", "TIỀN HƯỚNG", "cầu tiến, lạc quan"],
    [248, "ようきな", "陽気な", "DƯƠNG KHÍ", "cởi mở, hồ hởi, nắng ấm"],
    [249, "わかわかしい", "若々しい", "NHƯỢC", "trẻ trung, đầy sức sống"],
    [250, "びんかんな", "敏感な", "MẪN CẢM", "mẫn cảm, nhạy cảm"],
    [251, "ゆうかんな", "勇敢な", "DŨNG CẢM", "dũng cảm, can đảm"],
    [252, "むくちな", "無口な", "VÔ KHẨU", "ít nói"],
    [253, "りこうな", "利口な", "LỢI KHẨU", "thông minh, lanh lợi"],
    [254, "あほうな", "あほうな", "NGU", "khờ dại, ngu ngốc"],
    [255, "おくびょうな", "臆病な", "ỨC BỆNH", "nhát gan"],
    [256, "ようちな", "幼稚な", "ẤU TRĨ", "trẻ con, ấu trĩ, sự nhi"],
    [257, "みじゅくな", "未熟な", "VỊ THỤC", "chưa trưởng thành, non nớt"],
    [258, "ひんじゃくな", "貧弱な", "BẦN NHƯỢC", "nghèo, gầy yếu"],
    [259, "あわれな", "哀れな", "AI", "đáng thương, bi ai"],
    [260, "なまいきな", "生意気な", "SANH Ý KHÍ", "trơ tráo, hỗn láo, tinh tướng..."],
    [261, "あつかましい", "厚かましい", "HẬU", "đanh đá, mặt dày, đùa giả"],
    [262, "らんぼうな", "乱暴な", "LOẠN BẠO", "thô lỗ, cục cằn, thô bạo"],
    [263, "りこてきな", "利己的な", "LỢI KỈ ĐÍCH", "ích kỷ"],
    [264, "ごうまんな", "傲慢な", "NGẠO MẠN", "ngạo mạn, lão xược"],
    [265, "ひきょうな", "卑怯な", "TI KHIẾP", "chơi bẩn, gian xảo"],
    [266, "むちゃな", "無茶な", "VÔ TRÀ", "quá đáng, liều lĩnh, nóng nảy"],
    [267, "やかましい", "", "", "ồn ào, hay lèm bèm, khó tính"],
    [268, "やかましい", "", "", "ầm ĩ, phiền hà, ồn ào"],
    [269, "だいたんな", "大胆な", "ĐẠI ĐẢM", "Gan dạ, táo bạo"],
    [270, "けいかいな", "軽快な", "KHINH KHOÁI", "Nhịp nhàng, du dương"],
    [271, "びんしょうな", "敏捷な", "CỨNG KHOÁI", "Gọn gàng, chớp nhoáng"],
    [272, "ちゅうじつな", "忠実な", "TRUNG THỰC", "Chân thực, trung thành"],
    [273, "あやふやな", "あやふやな", "", "Mập mờ, mơ hồ, quanh co"],
    [274, "ざんこくな", "残酷な", "TÀN KHỐC", "Độc ác, dã man, ghê rợn"],
    [275, "ひさんな", "悲惨な", "BI THẢM", "Bi thảm"],
    [276, "なさけない", "情けない", "TÌNH", "đáng thương, thảm hại"],
    [277, "ねづよい", "根強い", "CĂN CƯỜNG", "Sâu sắc, ăn sâu vào..."],
    [278, "みっせつな", "密接な", "MẬT TIẾP", "Mật thiết"],
    [279, "かんだいな", "寛大な", "KHOAN ĐẠI", "Rộng lượng, phóng khoáng"],
    [280, "そぼくな", "素朴な", "", "Thích hợp, tương ứng"],
    [281, "ないこうな", "内向な", "NỘI TÂM", "Nội tâm, thầm lặng"],
    [282, "やるき", "やる気", "KHÍ", "Đam mê, động lực, hứng thú"],
    [283, "ゆうえつかん", "優越感", "ƯU VIỆT CẢM", "Tư cao tự đại"],
    [284, "おとり", "劣り", "KHOA", "Tụt hậu"],
    [285, "けつだん", "決断", "QUYẾT ĐOÁN", "Quyết định, quyết đoán"],
    [286, "くしん", "苦心", "KHỔ TÂM", "Cần cù, khó nhọc"],
    [287, "しっと", "嫉妬", "TẬT ĐỐ", "Ghen tị, đố kỵ"],
    [288, "ぜつぼう", "絶望", "TUYỆT VỌNG", "Tuyệt vọng"],
    [289, "つうかん", "痛感", "THỐNG CẢM", "Thấm thía"],
    [290, "せんにゅうかん", "先入観", "TIỀN NHẬP QUAN", "Thành kiến, định kiến"],
    [291, "あやまち", "過ち", "QUÁ", "Sai lầm, lỗi lầm"],
    [292, "よく", "欲", "DUC", "Mong muốn, tham vọng"],
    [293, "はじ", "恥", "SỈ", "Xấu hổ"],
    [294, "ばつ", "罰", "PHẠT", "Phạt"],
    [295, "ねん", "念", "NIỆM", "Chú ý, tâm niệm, để tâm"],
    [296, "ほんね", "本音", "BỔN ÂM", "Thật tâm"],
    [297, "べんかい", "弁解", "BIỆN GIẢI", "Lời bào chữa, biện minh"],
    [298, "ちんもく", "沈黙", "TRẦM MẶC", "Yên lặng"],
    [299, "ぼっとう", "没頭", "MỘT ĐẦU", "Chìm đắm, đắm chìm"],
    [300, "せんねん", "専念", "CHUYÊN NIỆM", "Chuyên tâm, tập trung vào"]
];