export const vocabList = [
    [1, "せいしゅん", "青春", "THANH XUÂN", "thanh xuân, tuổi trẻ"],
    [2, "ばんねん", "晩年", "VÃN NIÊN", "cuối đời"],
    [3, "そうしき", "葬式", "TÁNG THÚC", "đám tang"],
    [4, "せたい", "世帯", "THẾ ĐỚI", "hộ gia đình"],
    [5, "せけん", "世間", "THẾ GIAN", "thế gian, xã hội"],
    [6, "しょみん", "庶民", "THỨ DÂN", "dân thường"],
    [7, "おんぶ", "（なし）", "（なし）", "cõng, địu"],
    [8, "かたこと", "片言", "PHIẾN NGÔN", "kiến thức nông cạn, bập bẹ"],
    [9, "よふかし", "夜更かし", "DẠ CANH", "thức khuya"],
    [10, "いえで", "家出", "GIA XUẤT", "bỏ nhà"],
    [11, "とじまり", "戸締まり", "HỘ ĐẾ", "khóa cửa, sự đóng cửa"],
    [12, "ずぶぬれ", "ずぶ濡れ", "—", "ướt đẫm, ướt sũng"],
    [13, "かおつき", "顔つき", "NHAN", "biểu cảm khuôn mặt, vẻ mặt"],
    [14, "みなり", "身なり", "THÂN", "ngoại hình"],
    [15, "みのまわり", "身の回り", "THÂN HỒI", "việc thường ngày"],
    [16, "みぶり", "身振り", "THÂN CHÂN", "cử chỉ điệu bộ"],
    [17, "りょうしん", "良心", "LƯƠNG TÂM", "lương tâm"],
    [18, "そしつ", "素質", "TỐ CHẤT", "Năng khiếu, tố chất"],
    [19, "こうい", "好意", "HẢO Ý", "Ưu ái, mến mộ"],
    [20, "ためいき", "ため息", "TỨC", "thở dài"],
    [21, "どわすれ", "ど忘れ", "VONG", "chợt quên"],
    [22, "ようじん", "用心", "DỤNG TÂM", "cẩn trọng, đề phòng, cảnh giác"],
    [23, "よかん", "予感", "DỰ CẢM", "dự cảm"],
    [24, "しせん", "視線", "THỊ TUYẾN", "ánh nhìn"],
    [25, "めいしん", "迷信", "MÊ TÍN", "mê tín"],
    [26, "えん", "縁", "DUYÊN", "duyên, vận"],
    [27, "つかいすて", "使い捨て", "SỬ XÁ", "dùng một lần"],
    [28, "したどり", "下取り", "HẠ THỦ", "Đổi cũ lấy mới (có bù thêm tiền)"],
    [29, "けんやく", "倹約", "KIỆM ƯỚC", "tiết kiệm"],
    [30, "しゅっぴ", "出費", "XUẤT PHÍ", "chi phí"],
    [31, "かいけい", "会計", "HỘI KẾ", "Thanh toán, tính tiền"],
    [32, "しょとく", "所得", "SỞ ĐẮC", "Thu nhập"],
    [33, "さいよう", "採用", "THÁI DỤNG", "Thuê mướn, tuyển dụng"],
    [34, "こよう", "雇用", "CỐ DỤNG", "Tuyển dụng"],
    [35, "しょぞく", "所属", "SỞ THUỘC", "Thuộc về, nằm trong, trực thuộc"],
    [36, "たいぐう", "待遇", "ĐÃI NGỘ", "Đãi ngộ"],
    [37, "はけん", "派遣", "PHÁI KHIỂN", "Phái đi, phái cử"],
    [38, "ふにん", "赴任", "PHÓ NHIỆM", "Nhận chức (ở nơi khác)"],
    [39, "じもと", "地元", "ĐỊA NGUYÊN", "Địa phương, quê quán"],
    [40, "げんえき", "現役", "HIỆN DỊCH", "Đương chức"],
    [41, "さしず", "指図", "CHỈ ĐỒ", "Ra lệnh, chỉ dẫn"],
    [42, "そうさ", "操作", "THAO TUNG", "Điều hành, điều khiển"],
    [43, "しゅしょく", "主食", "CHỦ THỰC", "Món chính"],
    [44, "しょくもつ", "食物", "THỰC VẬT", "Đồ ăn, thực phẩm"],
    [45, "こくもつ", "穀物", "CỐC VẬT", "Ngũ cốc"],
    [46, "ほうさく", "豊作", "PHONG TÁC", "Mùa màng bội thu"],
    [47, "れいねん", "例年", "LIỆT NIÊN", "Hằng năm"],
    [48, "たね", "種", "CHỦNG", "Chủng, loại, hạt, nguồn gốc"],
    [49, "とげ", "棘", "—", "Gai, dằm"],
    [50, "どく", "毒", "ĐỘC", "Độc hại, chất độc"],
    [51, "くじ", "くじ", "", "Bốc thăm, xổ số"],
    [52, "けた", "桁", "HÀNH", "Kí tự, con số, đơn vị"],
    [53, "たんい", "単位", "ĐƠN VỊ", "Đơn vị"],
    [54, "いっかつ", "一括", "NHẤT QUÁT", "Hàng loạt, 1 lần"],
    [55, "かたまり", "塊/固まり", "CỤ", "Tảng, cục, miếng"],
    [56, "たけ", "丈", "TRƯỢNG", "Chiều dài, vạt áo"],
    [57, "らん", "欄", "LAN", "Cột ô, chuyên mục"],
    [58, "すみ", "隅", "ÔI", "Góc, xó"],
    [59, "ふち", "縁", "DUYÊN", "Mép, viền"],
    [60, "ひび", "罅", "", "Nứt"],
    [61, "ぶんれつ", "分裂", "PHÂN LIỆT", "Phân chia, chia rẽ"],
    [62, "しんどう", "振動", "CHẤN ĐỘNG", "Chấn động, rung lắc"],
    [63, "ふっとう", "沸騰", "PHÍ ĐẰNG", "Sôi, đỉnh điểm"],
    [64, "じゅんかん", "循環", "TUẦN HOÀN", "Tuần hoàn"],
    [65, "かいしゅう", "回収", "HỒI THU", "Thu hồi"],
    [66, "かくとく", "獲得", "HOẠCH ĐẮC", "Thu được, nhận được"],
    [67, "くかん", "区間", "KHU GIAN", "Đoạn, khoảng cách, khu vực"],
    [68, "しせつ", "施設", "THI THIẾT", "Cơ sở, thiết bị"],
    [69, "うんえい", "運営", "VẬN DOANH", "Quản lý, vận hành"],
    [70, "めんかい", "面会", "DIỆN HỘI", "Gặp gỡ"],
    [71, "へんきゃく", "返却", "PHẢN KHƯỚC", "Hoàn trả, trả lại"],
    [72, "とうしょ", "投書", "ĐẦU THƯ", "Thư góp ý, ý kiến bạn đọc"],
    [73, "けんさく", "検索", "KIỂM SÁCH", "Tra cứu, tìm kiếm"],
    [74, "ふしょう", "負傷", "PHỤ THƯƠNG", "Bị thương, chấn thương"],
    [75, "かんせん", "感染", "CẢM NHIỄM", "Lây nhiễm"],
    [76, "さよう", "作用", "TÁC DỤNG", "Tác dụng, tác động"],
    [77, "いぞん", "依存", "Ỷ TỒN", "Phụ thuộc, lệ thuộc"],
    [78, "かいしょう", "解消", "GIẢI TIÊU", "Giải quyết, hủy bỏ, xóa bỏ"],
    [79, "そくしん", "促進", "XÚC TIẾN", "Thúc đẩy"],
    [80, "いこう", "意向", "Ý HƯỚNG", "Chí hướng, dự định"],
    [81, "いと", "意図", "Ý ĐỒ", "Ý đồ, mục đích"],
    [82, "こうじょう", "向上", "HƯỚNG THƯỢNG", "Nâng cao, cải thiện"],
    [83, "かっき", "活気", "HOẠT KHÍ", "Hoạt bát, sôi nổi"],
    [84, "はくりょく", "迫力", "BÁCH LỰC", "Lôi cuốn, quyến rũ"],
    [85, "しょうり", "勝利", "THẮNG LỢI", "Chiến thắng"],
    [86, "てきおう", "適応", "THÍCH ỨNG", "Thích ứng"],
    [87, "ちょうわ", "調和", "ĐIỀU HÒA", "Điều hòa, hài hòa, hòa hợp"],
    [88, "けんりょく", "権力", "QUYỀN LỰC", "Oai quyền, khí thế"],
    [89, "けんい", "権威", "QUYỀN UY", "Uy quyền, danh giá"],
    [90, "あっぱく", "圧迫", "ÁP BÁCH", "Áp bức, bó chặt, sức ép"],
    [91, "きょうせい", "強制", "CƯỠNG CHẾ", "Cưỡng chế"],
    [92, "きせい", "規制", "QUY CHẾ", "Giới hạn, quy chế, hạn chế"],
    [93, "きょひ", "拒否", "CỰ PHỦ", "Cự tuyệt, từ chối"],
    [94, "たいこう", "対抗", "ĐỐI KHÁNG", "Đối đầu, ganh đua, cạnh tranh"],
    [95, "こうぎ", "抗議", "KHÁNG NGHỊ", "Kiếu nại, phản đối, phản nàn"],
    [96, "かくしん", "革新", "CÁCH TÂN", "Đổi mới"],
    [97, "げんそく", "原則", "NGUYÊN TẮC", "Nguyên tắc"],
    [98, "けいか", "経過", "KINH QUA", "Quá trình, trải qua"],
    [99, "ちゅうけい", "中継", "TRUNG KẾ", "Phát thanh, phát sóng, truyền hình"],
    [100, "きぼ", "規模", "QUY MÔ", "Quy mô"],
];