export const vocabList4 = [
    [301, "じゅうじつ", "充実", "SUNG THỰC", "Đầy đủ, trọn vẹn, ý nghĩa"],
    [302, "じりつ", "自立", "TỰ LẬP", "Tự lập"],
    [303, "そうご", "相互", "TƯƠNG HỖ", "Hỗ trợ nhau, tương hỗ"],
    [304, "きょうかん", "共感", "CỘNG CẢM", "Đồng cảm"],
    [305, "きょうちょう", "協調", "HIỆP ĐIỀU", "Hiệp lực, phối hợp"],
    [306, "きょうどう", "共同", "CỘNG ĐỒNG", "Dùng chung, cộng tác"],
    [307, "げきれい", "激励", "KÍCH LỆ", "Động viên, khích lệ"],
    [308, "しえん", "支援", "CHI VIỆN", "Hỗ trợ, ủng hộ"],
    [309, "してき", "指摘", "CHỈ TRÍCH", "Chỉ ra, chỉ trích"],
    [310, "りょうかい", "了解", "LIỄU GIẢI", "Hiểu rõ, tuân lệnh"],
    [311, "しょうだく", "承諾", "THỪA NẶC", "Đồng ý, nhận lời"],
    [312, "こびる", "媚びる", "HIỂM", "Quỵ lụy, làm phiền"],
    [313, "ぼうがい", "妨害", "PHƯƠNG HẠI", "Làm phiền, quấy rối, cản trở"],
    [314, "せっとく", "説得", "THUYẾT ĐẮC", "Thuyết phục"],
    [315, "りくつ", "理屈", "LÍ KHUẤT", "Lý do, hợp lý"],
    [316, "ろんり", "論理", "LUẬN LÍ", "Luận lý, logic"],
    [317, "すいり", "推理", "THÔI LÍ", "Suy luận, lập luận"],
    [318, "こんきょ", "根拠", "CĂN CỨ", "Căn cứ, lí do"],
    [319, "こちょう", "誇張", "KHOA TRƯƠNG", "Phóng đại, khoa trương"],
    [320, "あんじ", "暗示", "ÁM KÌ", "Ám hiệu, ám chỉ, hiểu ngầm"],
    [321, "さっかく", "錯覚", "THÁC GIÁC", "Ảo giác, nhầm lẫn"],
    [322, "しや", "視野", "THỊ DÃ", "Tầm nhìn"],
    [323, "くうはく", "空白", "KHÔNG BẠCH", "Trống không"],
    [324, "せっしょく", "接触", "TIẾP XÚC", "Tiếp xúc, va chạm"],
    [325, "こうしょう", "交渉", "GIAO THIỆP", "Đàm phán, thương lượng"],
    [326, "だきょう", "妥協", "THỎA HIỆP", "Thỏa hiệp, thỏa thuận"],
    [327, "こうしん", "更新", "CANH TÂN", "Cập nhật, gia hạn"],
    [328, "せいさん", "精算", "THANH TOÁN", "Thanh toán, điều chỉnh"],
    [329, "そんがい", "損害", "TỔN HẠI", "Tổn hại, hư hỏng"],
    [330, "りがい", "利害", "LỢI HẠI", "Lợi và hại, được mất"],
    [331, "こうけい", "光景", "QUANG CẢNH", "Quang cảnh, cảnh tượng"],
    [332, "ほうどう", "報道", "BÁO ĐẠO", "Thông tấn, báo cáo"],
    [333, "はかい", "破壊", "PHÁ HOẠI", "Phá hoại, hủy diệt"],
    [334, "はき", "破棄", "PHÁ KHÍ", "Hủy bỏ, bác bỏ, tiêu hủy"],
    [335, "たいおう", "対応", "ĐỐI ỨNG", "Ứng phó, giải quyết, đảm nhận"],
    [336, "たいしょ", "対処", "ĐỐI XỬ", "Ứng phó, đối phó"],
    [337, "とりひき", "取引", "THỦ DẪN", "Giao dịch, mua bán, làm ăn"],
    [338, "どくせん", "独占", "ĐỘC CHIẾM", "Độc chiếm, độc quyền"],
    [339, "しんしゅつ", "進出", "TIẾN XUẤT", "Đầu tư, vươn ra thị trường"],
    [340, "しんか", "進化", "TIẾN HÓA", "Phát triển, cải tiến"],
    [341, "いっさい", "一切", "NHẤT THIẾT", "Hoàn toàn không, nhất thiết"],
    [342, "かげん", "加減", "GIA GIẢM", "Của thả, vô trách nhiệm, tình trạng, giảm điều tiết..."],
    [343, "さくげん", "削減", "TƯỚC GIẢM", "Giảm thiểu, cắt giảm"],
    [344, "よぶん", "余分", "DƯ PHẦN", "Thừa ra, dư thừa"],
    [345, "よち", "余地", "DƯ ĐỊA", "Không chỗ trống, không có cơ hội"],
    [346, "はつげん", "発言", "PHÁT NGÔN", "Phát ngôn, lời lẽ"],
    [347, "はっこう", "発行", "PHÁT HÀNH", "Phát hành, cấp (giấy phép)"],
    [348, "はっしん", "発信", "PHÁT TÍN", "Truyền tải, phát ra, gửi"],
    [349, "はっそう", "発送", "PHÁT TỐNG", "Gửi đi"],
    [350, "はっこう", "発酵", "PHÁT DIÊU", "Lên men"],
    [351, "はついく", "発育", "PHÁT DỤC", "Trưởng thành, sự phát triển"],
    [352, "ほっそく", "発足", "PHÁT TÚC", "Thành lập, xuất phát, khởi đầu..."],
    [353, "かくしん", "確信", "XÁC TÍN", "Tin rằng, tin tưởng"],
    [354, "かくてい", "確定", "XÁC ĐỊNH", "Xác nhận, xác định"],
    [355, "かくほ", "確保", "XÁC BẢO", "Duy trì, giữ"],
    [356, "かくりつ", "確立", "XÁC LẬP", "Xác lập, thành lập"],
    [357, "はんのう", "反応", "PHẢN ỨNG", "Phản ứng"],
    [358, "はんしゃ", "反射", "PHẢN XẠ", "Phản xạ, phản quang"],
    [359, "はんぱつ", "反発", "PHẢN PHÁT", "Nổi loạn, phản đối lại"],
    [360, "はんきょう", "反響", "PHẢN ẢNH", "Phản âm, đáp lại (kì vọng)"],
    [361, "はんらん", "反乱", "PHẢN LOẠN", "Phản kháng, nổi loạn"],
    [362, "とっきょ", "特許", "ĐẶC HỨA", "Bằng sáng chế"],
    [363, "とくゆう", "特有", "ĐẶC HỮU", "Tiêu biểu, độc nhất"],
    [364, "とくてい", "特定", "ĐẶC ĐỊNH", "Đặc thù, cố định"],
    [365, "ふっき", "復帰", "PHỤC QUY", "Quay lại, trở lại, khôi phục"],
    [366, "ふっきゅう", "復旧", "PHỤC CỰU", "Phục hồi (về trạng thái cũ)"],
    [367, "ふっこう", "復興", "PHỤC HƯNG", "Phục hưng (tạo dựng lại)"],
    [368, "ついきゅう", "追及", "TRUY CẬP", "Truy cứu"],
    [369, "ついきゅう", "追求", "TRUY CẦU", "Theo đuổi, tìm kiếm"],
    [370, "ついきゅう", "追究", "TRUY CỨU", "Nghiên cứu, làm rõ"],
    [371, "ついせき", "追跡", "TRUY TÍCH", "Lần theo dấu vết, truy đuổi"],
    [372, "てほん", "手本", "THỦ BẢN", "Hình mẫu, mẫu để làm theo"],
    [373, "てがかり", "手がかり", "THỦ", "Manh mối"],
    [374, "てわけ", "手分け", "THỦ PHÂN", "Phân chia lao động, phân chia công việc"],
    [375, "てはい", "手配", "THỦ PHỐI", "Chuẩn bị, sắp xếp"],
    [376, "てさぐり", "手探り", "THỦ THAM", "Lần mò, tìm kiếm bằng tay"],
    [377, "てぎわ", "手際", "THỦ TẾ", "Tay nghề, kỹ năng xử lý"],
    [378, "にんき", "人気", "NHÂN KHÍ", "Phổ biến, được yêu thích"],
    [379, "ひとけ", "人気", "NHÂN KHÍ", "Bóng dáng người"],
    [380, "にんき", "人気", "NHÂN KHÍ", "Phổ biến, được yêu thích (lặp lại)"],
    [381, "ひとけ", "人気", "NHÂN KHÍ", "Bóng dáng người (lặp lại)"],
    [382, "いえで", "家出", "GIA XUẤT", "Bỏ nhà đi"],
    [383, "しゅっさん", "出産", "XUẤT SẢN", "Sinh đẻ"],
    [384, "しゅっせ", "出世", "XUẤT THẾ", "Thành đạt, thăng tiến"],
    [385, "しゅっぴ", "出費", "XUẤT PHÍ", "Chi tiêu, chi phí"],
    [386, "さよう", "作用", "TÁC DỤNG", "Tác dụng"],
    [387, "さよう", "作用", "TÁC DỤNG", "Tác dụng (lặp lại)"],
    [388, "さよう", "作用", "TÁC DỤNG", "Tác dụng (lặp lại)"],
    [389, "ふくさよう", "副作用", "PHÓ TÁC DỤNG", "Tác dụng phụ"],
    [390, "いぞん", "依存", "Y TỒN", "Phụ thuộc"],
    [391, "いそん", "依存", "Y TỒN", "Phụ thuộc (cách đọc khác)"],
    [392, "たいおう", "対応", "ĐỐI ỨNG", "Đối ứng, xử lý"],
    [393, "たいおう", "対応", "ĐỐI ỨNG", "Đối ứng, xử lý (lặp lại)"],
    [394, "たいおう", "対応", "ĐỐI ỨNG", "Đối ứng, xử lý (lặp lại)"],
    [395, "おうたい", "応対", "ỨNG ĐỐI", "Ứng xử, trả lời"],
    [396, "たいおう", "対応", "ĐỐI ỨNG", "Đối ứng, xử lý (lặp lại)"],
    [397, "たいおう", "対応", "ĐỐI ỨNG", "Đối ứng, xử lý (lặp lại)"],
    [398, "たいおう", "対応", "ĐỐI ỨNG", "Đối ứng, xử lý (lặp lại)"],
    [399, "たいおう", "対応", "ĐỐI ỨNG", "Đối ứng, xử lý (lặp lại)"],
    [400, "たいおう", "対応", "ĐỐI ỨNG", "Đối ứng, xử lý (lặp lại)"]
];